package com.trunarrative.exercise.searchcompany.web.model.company;

import lombok.Builder;
import lombok.Getter;

import java.util.List;

/**
 * This is the response generated by the Company Search API.
 */
@Builder
@Getter
public class SearchCompanyResponse {

    private int totalResults;
    private List<CompanyDetails> items;

    @Builder
    @Getter
    public static class CompanyDetails {
        private String companyNumber;
        private String companyType;
        private String title;
        private String companyStatus;
        private String dateOfCreation;
        private Address address;
        private List<Officers> officers;
    }

    @Builder
    @Getter
    public static class Officers {
        private String name;
        private String officerRole;
        private String appointedOn;
        private Address address;
    }

    @Builder
    @Getter
    public static class Address {
        private String locality;
        private String postalCode;
        private String premises;
        private String addressLine1;
        private String country;
    }
}
